[project]
name = "ai-video-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.5.9",
    "deep-translator>=1.11.4",
    "ffmpeg>=1.4",
    "ffmpeg-python>=0.2.0",
    "ffprobe>=0.5",
    "fpdf2>=2.8.7",
    "huggingface-hub>=1.14.0",
    "langchain>=1.2.18",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.1",
    "langchain-core>=1.4.0",
    "langchain-huggingface>=1.2.2",
    "langchain-mistralai>=1.1.4",
    "mistralai>=2.4.5",
    "numpy>=2.4.4",
    "openai-whisper>=20250625",
    "pydub>=0.25.1",
    "python-dotenv>=1.2.2",
    "reportlab>=4.5.1",
    "requests>=2.34.0",
    "sentence-transformers>=5.4.1",
    "streamlit>=1.57.0",
    "streamlit-extras>=1.5.0",
    "tiktoken>=0.12.0",
    "torch>=2.11.0",
    "torchaudio>=2.11.0",
    "torchvision>=0.26.0",
    "tqdm>=4.67.3",
    "watchdog>=6.0.0",
    "yt-dlp>=2026.3.17",
]
